apiVersion: v2
type: application
appVersion: latest
version: 1.0.0
name: mautrix-wsproxy
description: A simple HTTP push -> websocket proxy for Matrix appservices
keywords:
  - mautrix-wsproxy
home: https://mau.dev/mautrix/wsproxy/
sources:
  - https://mau.dev/mautrix/wsproxy/
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "use tcp healthchecks ([fb7066b](https://github.com/halkeye-helm-charts/mautrix-wsproxy/commit/fb7066b04d971adda3d67e1076f3d08f4f4fb0e3))"
     - "variable names ([30ec1a3](https://github.com/halkeye-helm-charts/mautrix-wsproxy/commit/30ec1a378ec70ad33021cebeb2784e7b8631ac16))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: wsproxy
      image: dock.mau.dev/mautrix/wsproxy:latest
